### ISSUE TITLE
Backspace bug

### ISSUE THREAD

**Issue by Daniel-Cher** [Willard21/MineKhan#103]
When ever I press backspace the game crashes. Here's a screenshot:
![image](https://user-images.githubusercontent.com/105668774/168673982-d674f2bc-9bde-4ede-97b4-6a58b4e07fbe.png)

**Comment by ImaginaryNeon** [comment]
Could you show a video so we can see what was going on beforehand?

**Comment by Willard21** [comment]
Nothing special. Just hit backspace and it crashes lol. Pretty easy to reproduce.

**Comment by ImaginaryNeon** [comment]
> Nothing special. Just hit backspace and it crashes lol. Pretty easy to reproduce.

I meant what menu/"state" you had to be in. I reproduced it, and it only seems to happen after loading a world.

https://user-images.githubusercontent.com/92883596/168813887-0dc22756-513c-409c-9730-def93dc1f1ab.mp4

**Comment by ImaginaryNeon** [comment]
The pauses are me checking by backspacing.

**Comment by Willard21** [comment]
Fair enough. In this case I knew that the backspace key only does anything in the game scene. It's supposed to throw a block on the ground, but that was mainly a proof-of-concept feature in the first place (since there's no inventory), so I forgot to test it after making changes to the Entity class.

**Comment by Willard21** [comment]
I commented out the "drop block" code, so it no longer crashes.
