### ISSUE TITLE
MineKhan Server's .

### ISSUE THREAD

**Issue by SnehasishCodez** [Willard21/MineKhan#26]
In my opinion server should be fixed since after the host logs out of the server the server just shuts down willard should create a seperate site where all the server are linked and you can join one

**Comment by Willard21** [comment]
The only way that would work would be if the world was hosted server-side. I have very limited server-side resources, so that's not practical or scalable. Real Minecraft uses a dedicated server for every single world, and most people pay $20 - $30 per month to keep 1 server running. Anyone with that kind of money already owns the real Minecraft, so there's no point in trying to set it up like that.
