### ISSUE TITLE
I banned myself

### ISSUE THREAD

**Issue by thingMake** [Willard21/MineKhan#35]
So I had bad internet and I was on willard.fun, 
I opened a world to public and joined on another device.
And then it said Connection lost so I opened it to public again. 
Then I opened the developer tools to see what was going on and it sayed the host banned me.

It shouldn't be banning me because I was the host and I didn't ban anyone.

**Comment by Willard21** [comment]
Eh you weren't actually banned. I just didn't write a proper error message for it. I don't allow the same account to be in the same world multiple times at once, since it would cause you to teleport between all your own positions to anyone else in the world. I'll fix the error message when I get around to it.
