### ISSUE TITLE
banned forever lol

### ISSUE THREAD

**Issue by sauron65** [Willard21/MineKhan#47]
![Screenshot 2021-06-18 10 54 09](https://user-images.githubusercontent.com/72841060/122599735-aa07c200-d023-11eb-9bfa-97783b6f83f1.png)

even in the source code:

![Screenshot 2021-06-18 10 54 18](https://user-images.githubusercontent.com/72841060/122599710-a2481d80-d023-11eb-92ed-ecfad47c2dc3.png)

on every single page.

this happened because  I tried to make an alt account, then I tried to login on my regular account after seeing this (sup6666)

**Comment by BrendaPuckle** [comment]
how did that happen?

**Comment by BrendaPuckle** [comment]
lol?

**Comment by BrendaPuckle** [comment]
who's hacking?

**Comment by Willard21** [comment]
3 accounts were made on the same IP in under a minute, which triggered an IP ban. Brenda_Puckle, MyHat3, and sup6666. I'll remove the ban since you appear to be different people. I was having some trouble with a script kiddie yesterday spamming accounts so fast it crippled the entire site, so I added some strict rate limits. I'll increase the cap to 5 just to be safe. Sorry for the inconvenience.
