### ISSUE TITLE
Randomly unable to access multiplayer

### ISSUE THREAD

**Issue by SuperNova841** [Willard21/MineKhan#61]
Sometimes, I can't access multiplayer features; when I try to join or host a server, I get the "Connection lost!" error instantly. However, I see working servers, so others don't have this problem. If needed, I can post a few system specifications.

**Comment by Willard21** [comment]
Hit F12 to view the dev console and see if there's any errors when you open a world. If you tried to spam a multiplayer server in the last week, it may have auto banned you. If that's the case, it's not permanent and will go away next time I restart the website.

**Comment by SuperNova841** [comment]
The only warning in the console is "[Violation] 'close' handler took ####ms", both for joining and hosting a world. And I haven't spammed any server... Is it relevant that both times this has happened to me begun with one of my servers (with players) getting disconnected?

**Comment by SuperNova841** [comment]
It just got fixed... if that was you, thanks, and if it wasn't... 😕

**Comment by Willard21** [comment]
I restarted the website for an unrelated issue earlier. But I just got home from work to check logs.
> Banned novacoding for spam.
novacoding closed world: hide & seek with 5 users

You were banned, and the restart cleared it. That happens if you send over 50 events to the server in under 50 milliseconds. If you were using a script to place/break blocks, make sure you have a delay between each block in the future. Super breaker can only break 1 block per 50 milliseconds, so I find it unlikely that a lag spike caused it, but if it did, then sorry.

**Comment by SuperNova841** [comment]
That makes sense; I was using my autoclick mouse a lot with a delay of only 5 milliseconds... Thanks for the info; I'll reconfigure it so it doesn't spam too much :)

**Comment by SuperNova841** [comment]
It just happened again, and I wasn't even doing anything :/

**Comment by SuperNova841** [comment]
I was just banned again, but I had configured my autoclick to be at the same speed as hyperbuilder. Also, how did you ensure alts didn't work either?
