### ISSUE TITLE
WebGL warnings when hotbar is empty

### ISSUE THREAD

**Issue by ghost** [Willard21/MineKhan#82]
When i empty my hotbar, the are warnings in the console.
Here is the warning: ```WebGL: INVALID_OPERATION: drawArrays: no buffer is bound to enabled attribute```

**Comment by Oranamous** [comment]
There is no buffer to bind since there are no items to render, therefore JavaScript throws errors that binding the buffer to webgl was unsuccessful.

**Comment by Willard21** [comment]
Actually it's the targeted block outline causing it. When an inventory item is rendered, block lighting is disabled first. Apparently it just stays disabled globally until the next time you unpause the game. Chunks are rendered with VAOs, so they don't use the global attribute settings, which is why I never noticed.

Anyway, the block outline doesn't pass a buffer for block lighting since it's just black. That's what causes the warning. The safest solution would probably be to disable it every frame before rendering the outline, but the completely unsafe solution with marginally better performance would be to leave lighting disabled permanently, and just hope I don't forget if I ever change anything.

**Comment by Willard21** [comment]
This is fixed
