### ISSUE TITLE
Lag Spikes in Main Menu

### ISSUE THREAD

**Issue by Mist-Stego** [Willard21/MineKhan#83]
I think the title sums it up. When I am on chrome, I use an FPS extension and at ~30 seconds, the lag spiked from a smooth 78 FPS to a catastrophic 6 FPS. I tested this out on different browsers, but all they did was either make my lag worse (from 70 FPS on Opera to 4 - 7 FPS), or it made it slightly better in my eyes (Now, Safari does not have any extension store so it was extremely hard for me to tell how many frames it was running at, but I can estimate it was around 80 FPS, and it dropped to 12 FPS).

I think it may be something to do with my computer being pretty bad, but please tell me if this is happening to you.

One thing to note, this ONLY happens on the main menu, not any other part of the GUI.

**Comment by Willard21** [comment]
I don't know what method your extension uses to determine if a frame is finished, but I would expect it to say 0 FPS instead. All the menus are updated from the mousemove event instead of in the render loop to reduce idle power consumption. In other words, if your mouse isn't moving across the screen, nothing is being rendered. Lag is impossible.
