### ISSUE TITLE
Error in comments

### ISSUE THREAD

**Issue by MicrolemurDev** [Willard21/MineKhan#84]
Towards the top of the HTML file you mention WebGL is able to allow your game to run as fast as any C++ game which is not true.

WebGL allows us to have hardware 3D Acceleration but we are still limited heavily by JavaScript's speed. This can be lightened by making the server in WASM and using WebWorkers but even on firefox WASM is only about 55% of the native speed in _best case scenarios_. This is just a small correction that should be made.

**Comment by Willard21** [comment]
You would be correct _if_ the game was limited by CPU speeds. However, it's not. On nearly every computer, the limiting factor is GPU processing speeds. While the data transfer layer has more overhead in JS than C++, that overhead is on the CPU. So as long as the CPU isn't at 100% usage, it won't slow it down at all.

OpenGL ES GPU shaders on a C++ program are exactly the same as WebGL GPU shaders on a JS program. So once the data gets to that layer, it's running at the same speeds. Since that layer is the bottleneck, the speeds are equivalent.
