### ISSUE TITLE
Wrong Menu Texture

### ISSUE THREAD

**Issue by Willard21** [Willard21/MineKhan#86]
When it's supposed to draw the dirt texture, it draws the blocks texture atlas instead. Affects the pause screen, main menu, and chat screens after resizing the window.
![image](https://cdn.discordapp.com/attachments/731003852970524715/916706901574713434/unknown.png)

**Comment by Mist-Stego** [comment]
Is there something happening when the browser is trying to render these menu screens? Because that may be the thing that is ruining them.

Is there anyway to manually make the screens when a specific key is pressed? That may allow you as a creator to manually ask the canvas / browser to render the dirt texture and additional text if necessary. 

Hope it helps :)

**Comment by thingMake** [comment]
It doesn't happen for me.

**Comment by Willard21** [comment]
The requirement is rendering an entity. Throwing a block in singleplayer will trigger it too.

**Comment by thingMake** [comment]
Try putting this: ```gl.bindTexture(gl.TEXTURE_2D, dirtTexture)``` after ```gl.uniform1i(glCache.uSampler2, 1)``` in initBackgronds

**Comment by Willard21** [comment]
Fixed now
