### ISSUE TITLE
Hosting multiplayer?

### ISSUE THREAD

**Issue by proudparrot2** [Willard21/MineKhan#88]
Is there a way we can host multiplayer for ourselves? Like with the login and everything.

**Comment by Willard21** [comment]
Only if you want to code the back-end yourself. It's pretty simple since there's no server-side processing outside of authentication. But I don't want to open source it, since I'm not really a big fan of lots of people hosting it.

**Comment by proudparrot2** [comment]
Can you email me a copy of it? I won’t post it anywhere, it’s just for me and my friends

**Comment by proudparrot2** [comment]
Plus I’m not that good at coding, so I couldn’t code like a whole auth backend sorry

**Comment by proudparrot2** [comment]
Hello???? @Willard21

**Comment by Mist-Stego** [comment]
@proudparrot2 

Since Willard doesn't want to make MineKhan open-source at the moment, you will have to code your own backend nodes and data holders. If you can't code it on your own, you will have to host a multiplayer server by using willard.fun

He won't give you a copy of the backend creators and code files due to the fact that he hasn't made it open-source lol

**Comment by proudparrot2** [comment]
I was trying to ask that to Willard, but ok
