### ISSUE TITLE
[Question] KA Version Refactoring

### ISSUE THREAD

**Issue by MicrolemurDev** [Willard21/MineKhan#90]
I know the KA Version isn't up to date but I have been playing with the source code and found that trying to split up the JavaScript causes huge console spam relating to the render context. I am curious how the source for this version was able to be split up without causing huge console error spam.

**TLDR: I am getting huge amounts of errors when trying to move the KA Version to multiple files. Why is this?**

**Comment by Willard21** [comment]
I assume you're running some initialization code more than you're supposed to or something. I can't answer questions about code I've never seen. Splitting code into multiple files on this project is a little complex because there's so many functions editing shared variables that aren't global. They're all in a big closure. Phi started splitting it up, and he mostly made it work by adding the shared variables to function parameters.

**Comment by MicrolemurDev** [comment]
Now I got past some first issues but still am now dealing with drawScreens[screen] not being found? Do you know where this is defined by any chance?

**Comment by Willard21** [comment]
This isn't an issue with this version so I'm closing it.
