### ISSUE TITLE
banned and I don't know why

### ISSUE THREAD

**Issue by proudparrot2** [Willard21/MineKhan#91]
Hi willard sorry that I have been opening so many issues but I showed minekhan to people at school so now like 5 people play it

I was playing and I switched my account (I have only like 3) and it said banned forever lol

now my friend just came to me saying that he was banned also and he only has one account

can you unban us plss we are not doing anything bad

**Comment by Willard21** [comment]
![image](https://user-images.githubusercontent.com/24826881/149183080-7deda65d-94f8-4727-a7d6-a5e26c222de8.png)
I assume this one was you. I'm showing these accounts tied to you. That seem about right?
![image](https://user-images.githubusercontent.com/24826881/149183175-23efa8e2-d3a6-4338-98e9-60b099c72add.png)

**Comment by proudparrot2** [comment]
Yes some of those are mine
I don't know why the other ones would be tied to me, but I certainly didn't login 20 times in 1 minute...

**Comment by proudparrot2** [comment]
My friend (Jamal sus) just told me that his brother (TeamTaki) signed in at home and never st school at still got banned. He didn’t have any alts. Any theories on how this happened?

**Comment by thingMake** [comment]
Maybe it detectected your friend using the school wifi

**Comment by proudparrot2** [comment]
Jamal sus didn't sign in on his home wifi though so how could that happen

**Comment by proudparrot2** [comment]
Ok so it appears that we are unbanned because we can access MineKhan again. I'm not gonna use any alts to prevent us getting banned again, so thank you.

Still, any idea why those accounts are linked to me?

**Comment by Willard21** [comment]
Ah yeah I guess I forgot to tell you I unbanned your IP. Anyway, as for TeamTaki, I keep an association graph for accounts so I can find alts of trouble-makers. You're right that he never logged in to the school wifi, but Jamal logged in both at school and at home, which caused Taki to be associated with him. The auto ban system doesn't look at that though, so it only banned the single school IP. Meaning TeamTaki was never banned.

Someone else at your school was spamming login attempts. You did identify a small bug, though. Someone else reached the ban threshold exactly, then didn't make another login attempt that day. Then you tried to login the next day after it had already decided to ban that IP, so it dropped the hammer on you instead of them. The end result was the same, but I'm sure it confused you. (Note the timestamps.)
![image](https://user-images.githubusercontent.com/24826881/149392500-e8ce4890-cc70-46bb-98d0-77434e44e972.png)

**Comment by proudparrot2** [comment]
Ok, this makes sense, thank you very much. I will be sure to tell them what happened.

If it happens again, can I recomment in this issue?

**Comment by proudparrot2** [comment]
Sweet thanks
