### ISSUE TITLE
Multiplayer bug (maybe).

### ISSUE THREAD

**Issue by LGrounds** [Willard21/MineKhan#92]
Hi Willard, I have a very weird bug when I try to play multiplayer. The bug has happened 2 or 3 times. I select a server, then press “play the selected world” and it does nothing at all. No loading screen, nothing. I then would try to play single player, which would allow me to enter my world, but this is where it gets really weird. I can see players moving around my world, even placing blocks. The players were NOT ghosts, as this world had never been made public. Each time this has happened, I would try to chat with the players, and ask them if they could see my world or not, but each time while I was typing, it would send me back to the home screen, and say “connection lost”. I assume what is happening is that the site/my computer lags, and when I select my single player world, I can see other players, but they are actually in their world but are somehow connected to mine? I don’t really know, and this is probably a problem on my end, but I just wanted to see what you thought. Also, you should know that this would happen a few times each time I tried to play multiplayer, but then would stop being weird, and allow me to play multiplayer.

**Comment by LGrounds** [comment]
Ok, so I have been doing a bit of multiplayer today, but just now I selected a server and it again did not work. I then went to my single-player world, and yes, there were a bunch of players there. I tried to talk to them, but they did not respond. I then closed the world (and it said connection lost). In the discord, it showed this:
![Screenshot (15)](https://user-images.githubusercontent.com/97562394/149414308-83235259-4060-40e2-b688-8700eeb33f51.png)

but what's weird is that it didn't show that I had opened a world, just that I had closed one. Again I'm guessing that this a probably a problem on my end, but I just don't know.

**Comment by Willard21** [comment]
That sounds interesting lol. So basically what's happening is that you're requesting a copy of the multiplayer world from the world's host. They're either not sending that copy of the world, or you're not receiving it, which is why it appears to not be responding. But regardless of if you're able to load the world, you're already connected to it server-side. Then when you go open a single player world, you're receiving position and block updates from players in the world you tried to connect to.

I'm not sure why the "closed world:  with 1 users" thing happens. It seems to think you're the world host, which is true client side, but not server-side since you weren't the one that initiated the multiplayer world. I *thought* that one happened when you tried to join a world after it closed, but if there were players moving around inside it, then that theory may be wrong.

**Comment by ImaginaryNeon** [comment]
Nobody:
The people you were seeing:
![2022_01_16_0sy_Kleki](https://user-images.githubusercontent.com/92883596/149704198-3b2fe8ed-3671-48f4-9416-527706192b18.png)

**Comment by Willard21** [comment]
Worlds now disconnect if the host can't respond to a ping, so it shouldn't keep you in limbo like that any more. Hopefully. If it still happens to anyone, they can open a new issue.
